version: "3"

services:
  bot:
    build: .
    # command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
    ports:
      - 8002:8000
    volumes:
      - /home/grixus/docker-froakbot/froak-db/:/app/froak-db/
